// LAST TESTED : 12/27/2019
#ifndef __CHANNEL_H__
#define __CHANNEL_H__
#include <xil_types.h>
void sobelWrite();
void yCbCrWrite();
void colorFilterFixed();
void colorFilterA11(u16 Axx);
void colorFilterA12(u16 Axx);
void colorFilterA13(u16 Axx);
void colorFilterA21(u16 Axx);
void colorFilterA22(u16 Axx);
void colorFilterA23(u16 Axx);
void colorFilterA31(u16 Axx);
void colorFilterA32(u16 Axx);
void colorFilterA33(u16 Axx);
void colorFilterKc(u16 Axx);
void SobelCoefsUpdate();
void SobelCoefX();
void SobelCoefY();
void PrewitCoefsUpdate();
void PrewitCoefX();
void PrewitCoefY();
void EmbosCoef();
void YcbcrCoef();
void SharpCoef();
void BlureCoef();
void CgainCoef();
void Cgain1Coef();
void Cgain2Coef();
void Cgain3Coef();
void Cgain4Coef();
void Cgain5Coef();
void Cgain6Coef();
void Cgain7Coef();
void prewittWrite();
void sobelEnable();
void prewittEnable();
void computeBrightness();
void pRbrightness();
void selected_channel();
void edge_threshold_val(u16 thresholdValue);
void videoFeatureSelect(u16 videoType);
void WrDataSd();
void edgeType(u16 edgeTypeValue);
void edgeColor(u16 edgeColorVal);
void cpuackgoagain(u16 valueIn);
void gridlock(u16 valueIn);
void readGData(u16 edgeTypeValue);
void color_correction(u16 videoType);
void ycbcrSelect(u16 videoType);
void deltaConfig(u16 videoType);
void framefifoMode(u16 fifoMode);
void point_Interest(u16 videoType);
void ReadDataByte(u16 Value);
void fifoStatus();
void read_gdata_continue_mode();
void readGDataStopMode();
void pointInterestFixed();
void framefifoFixed();
void vdma_hdmi_config();
void vfp_rgb_level_config();
void init_vdma_hdmi();
void write_to_vfp();
void d5m_init();
void d5mInitCall();
void d5mInitPrint();
void ycbcr_Disable();
void ycbcr_Enable();
u16 rColorFilterA11();
u16 rColorFilterA12();
u16 rColorFilterA13();
u16 rColorFilterA21();
u16 rColorFilterA22();
u16 rColorFilterA23();
u16 rColorFilterA31();
u16 rColorFilterA32();
u16 rColorFilterA33();
void readFifo();
void enableNextRead(u16 eValue);
void colorDetectRange(u16 fRgbCoordRL,u16 fRgbCoordRH,u16 fRgbCoordGL,u16 fRgbCoordGH,u16 fRgbCoordBL,u16 fRgbCoordBH);
void colorHsvPerChHsv();
void colorHsvPerChH();
void colorHsvPerChS();
void colorHsvPerChV();
void colorYCbCrCh();
void colorYCbCrPerChY();
void colorYCbCrPerChCb();
void colorYCbCrPerChCr();
void lum_ThresholdValue(u16 lumThresholdValue);
void lThSelect(u16 lumThresholdValue);
void rawRgbSelect(u16 rawRgbSelectValue);
void colorYCbCrPerCh(u16 PerChValue);
void colorHsvPerCh(u16 PerChValue);
void videokCoefValsUpdate(u16 testValues,int filterNumber);
#endif // __CHANNEL_H__