// LAST TESTED : 12/27/2019
#ifndef __CHANNEL_H__
#define __CHANNEL_H__
#include <xil_types.h>
void sobel_write();
void yCbCrWrite();
void color_filter_fixed();
void color_filter_a11(u16 Axx);
void color_filter_a12(u16 Axx);
void color_filter_a13(u16 Axx);
void color_filter_a21(u16 Axx);
void color_filter_a22(u16 Axx);
void color_filter_a23(u16 Axx);
void color_filter_a31(u16 Axx);
void color_filter_a32(u16 Axx);
void color_filter_a33(u16 Axx);
void color_filter_kc(u16 Axx);
void sobel_coef_update();
void sobel_coef_x();
void sobel_coef_y();
void prewit_coef_update();
void prewit_coef_x();
void prewit_coef_y();
void embos_coef();
void ycbcr_coef();
void sharp_coef();
void blur_coef();
void cgain_coef();
void cgain_1_coef();
void cgain_2_coef();
void cgain_3_coef();
void cgain_4_coef();
void cgain_5_coef();
void cgain_6_coef();
void cgain_7_coef();
void prewitt_write();
void sobelEnable();
void prewitt_enable();
void compute_brightness();
void update_brightness();
void selected_channel();
void edge_threshold_val(u16 thresholdValue);
void video_feature_select(u16 videoType);
void WrDataSd();
void edge_type(u16 edgeTypeValue);
void edge_color(u16 edgeColorVal);
void cpu_ack_go_again(u16 valueIn);
void grid_lock(u16 valueIn);
void read_gdata(u16 edgeTypeValue);
void color_correction(u16 videoType);
void ycbcr_select(u16 videoType);
void deltaConfig(u16 videoType);
void framefifoMode(u16 fifoMode);
void point_interest(u16 videoType);
void read_data_byte(u16 Value);
void fifo_status();
void read_gdata_continue_mode();
void read_gdata_stop_mode();
void point_interest_fixed();
void framefifoFixed();
void vdma_hdmi_config();
void vfp_rgb_level_config();
void init_vdma_hdmi();
void write_to_vfp();
void d5m_init();
void d5m_init_call();
void d5m_init_print();
void ycbcr_disable();
void ycbcr_enable();
u16 r_color_filter_a11();
u16 r_color_filter_a12();
u16 r_color_filter_a13();
u16 r_color_filter_a21();
u16 r_color_filter_a22();
u16 r_color_filter_a23();
u16 r_color_filter_a31();
u16 r_color_filter_a32();
u16 r_color_filter_a33();
void read_fifo();
void enable_next_read(u16 eValue);
void color_detect_range(u16 fRgbCoordRL, u16 fRgbCoordRH, u16 fRgbCoordGL,
        u16 fRgbCoordGH, u16 fRgbCoordBL, u16 fRgbCoordBH);
void color_hsv_per_ch_hsv();
void color_hsv_per_ch_h();
void color_hsv_per_ch_s();
void color_hsv_per_ch_v();
void color_ycbcr_ch();
void color_ycbcr_per_ch_y();
void color_ycbcr_per_ch_cb();
void color_ycbcr_per_ch_cr();
void lum_threshold_value(u16 lumThresholdValue);
void l_th_select(u16 lumThresholdValue);
void raw_rgb_select(u16 rawRgbSelectValue);
void color_ycbcr_per_ch(u16 PerChValue);
void color_hsv_per_ch(u16 PerChValue);
void video_kcoef_vals_update(u16 testValues, int filterNumber);
#endif // __CHANNEL_H__
